baseURL = "https://blog.kytrue.com/tangpoemnote/"
languageCode = "zh-CN"
title = "唐诗笔记"
theme = "hugo-kiera"
copyright = "Copyright &copy; 2021 - Kytrue"
canonifyurls = true
paginate = 8
summaryLength = 4
pygmentsCodeFences = true

[author]
    name = "Kytrue"
    github = "kytrue"

[params]
    tagline = "The best way to learn is to output! "

[[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts"
    weight = 1

[[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories"
    weight = 2

[[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags"
    weight = 3

[[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about"
    weight = 4
    